### ISSUE TITLE
Cannot compile RotaryEncoder

### ISSUE THREAD

**Issue by Bwoe** [tttapa/MIDI_controller#10]
When attempting to use "Single_potentiometer" within the IDE, the following error occurs:
`In file included from /Users/username/Documents/Arduino/libraries/MIDI_controller-2.1.0/src/MIDI_controller.h:9:0,
                 from /Users/username/Documents/Arduino/libraries/MIDI_controller-2.1.0/examples/Single_potentiometer/Single_potentiometer.ino:14:
/Users/username/Documents/Arduino/libraries/MIDI_controller-2.1.0/src/RotaryEncoder.h:6:21: fatal error: Encoder.h: No such file or directory
 #include "Encoder.h"
                     ^
compilation terminated.`
https://github.com/tttapa/MIDI_controller/blob/master/src/RotaryEncoder.h#L6

Changing "Encoder.h" to "RotaryEncoder.h" matches the filename in the subdirectory, but then throws the following:
`In file included from /Users/username/Documents/Arduino/libraries/MIDI_controller-2.1.0/src/MIDI_controller.h:9:0,
                 from /Users/username/Documents/Arduino/libraries/MIDI_controller-2.1.0/examples/Single_potentiometer/Single_potentiometer.ino:14:
/Users/username/Documents/Arduino/libraries/MIDI_controller-2.1.0/src/RotaryEncoder.h:45:3: error: 'Encoder' does not name a type
   Encoder enc;
   ^` 

Any suggestions?

**Comment by tttapa** [comment]
Read the installation instructions in the ReadMe.
