### ISSUE TITLE
Serial MIDI

### ISSUE THREAD

**Issue by Steamedmuffin** [tttapa/MIDI_controller#13]
## Description of the problem or question
can i send midi data through the Arduino Uno's USB Port?
if so how is this done?
## Steps to reproduce the problem
this is just an ordinary question ;)
### Hardware
Arduino Uno and a few potentiometers

### Software versions:

**MIDI Controller library**: ? 3.0.1   
**Arduino IDE**: ? 1.8.5   
**Operating System**:  Windows  
**Operating System version**: ? 10  

### Full code 

```cpp
// Your code here
```

## Steps taken to try to diagnose or solve the problem
? Tried the MIDI debug mode, used a MIDI monitor, ... ?

**Comment by tttapa** [comment]
Have you read the [Wiki](https://github.com/tttapa/MIDI_controller/wiki/MIDI-over-USB) and the [ReadMe](https://github.com/tttapa/MIDI_controller/blob/master/README.md)?
