### ISSUE TITLE
thanks for this library

### ISSUE THREAD

**Issue by squillmcgill** [tttapa/MIDI_controller#14]
Before opening a new issue, please read the [installation instructions](https://github.com/tttapa/MIDI_controller#installation) in the README. Also check if your question is answered in the [Wiki](https://github.com/tttapa/MIDI_controller/wiki) or in a [previous issue](https://github.com/tttapa/MIDI_controller/issues?q=is%3Aissue).   
If you do create a new issue, please follow the template below.  
--- (delete these first lines) ---

## Description of the problem or question

no actual problem, I was having a lot of issues getting a midi controller up and running and this guide/library was pretty comprehensive to get a simple controller going. Just wanted to say thanks, sorry if this isn't the correct place for that, fairly new to github as well

### Hardware

**Arduino board**:  ? Arduino UNO, Arduino Leonardo, Arduino DUE, Arduino MEGA, Arduino Micro, Teensy 3.2, ... ?  
**Schematic**: ?  

### Software versions:

**MIDI Controller library**: ? 3.0.0 ?  
**Arduino IDE**: ? 1.8.4 ?  
**Operating System**: ? Windows, OSX, Ubuntu, ... ?  
**Operating System version**: ? 10, 16.04, ... ?  
(**Teensyduino**): ? 1.39 ? 
(**Encoder library**): ? 1.4.1 ?  
(**MIDIUSB library**): ? 1.0.3 ? 

### Full code 

```cpp
// Your code here
```

## Steps taken to try to diagnose or solve the problem
? Tried the MIDI debug mode, used a MIDI monitor, ... ?

**Comment by tttapa** [comment]
Glad to hear!

(The issues section on GitHub is mostly used for bug reports or questions that are not answered by the documentation, but I appreciate your message!)
