### ISSUE TITLE
Can I receive values over midi?

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [tttapa/MIDI_controller#18]
## Can I receive values over MIDI?
Is there a way to receive MIDI values? As I can see in the examples, they all just send values over MIDI. But I can not find a example to receive values...

I want to have a kind of feedback. If my midi software changes a value, I want to receive this and light up some LEDs.
f.e. I want a LED-ring around my rotary encoder and want to highlight the current value.

### Hardware
**Arduino board**:  Arduino MEGA, Teensy 3.2

### Software versions:
**MIDI Controller library**: 3.0.0

**Comment by tttapa** [comment]
I have been working on a second library that supports MIDI input as well. However, it's not documented yet.
[https://github.com/tttapa/Control-Surface](https://github.com/tttapa/Control-Surface)

**Comment by devwmbr** [comment]
Will it be possible to receive bank name or preset name from guitar Amp simulator, e.g. GuitarRig, Overloud TH3 or similar?

**Comment by Jorgen-VikingGod** [comment]
great to see that some progress is coming.

**Comment by BBABO** [comment]
Thanks !

**Comment by mungewell** [comment]
Did you consider SysEx messages to 'just' set bytes within a memory?

I'm certainly not an expert, but in reversing a Akai MPD218 I can pretty much drive/control the device via SysEx.
