### ISSUE TITLE
MIDI read

### ISSUE THREAD

**Issue by hachimbala** [tttapa/MIDI_controller#24]
Hello,

I was eondering how I can do a MIDI.read() (or something similar) to read the MIDI messages that Traktor sends to the Arduino and then use it.

In my void setup I inicialized with MIDI.begin();
So now only with MIDI.read() can I get the MIDI messages that Traktor send to the Arduino?

Thank you so much!

**Comment by tttapa** [comment]
What board are you using?  
MIDI input is currently not supported.

**Comment by hachimbala** [comment]
Mega

**Comment by tttapa** [comment]
MIDI input is discarded by the library. You can just change this function to allow for MIDI input, and then use the MIDI library.
[https://github.com/tttapa/MIDI_controller/blob/master/src/MIDI_Interfaces/SerialMIDI_Interface.h#L11-L18](https://github.com/tttapa/MIDI_controller/blob/master/src/MIDI_Interfaces/SerialMIDI_Interface.h#L11-L18)

**Comment by hachimbala** [comment]
Ok, but how I can open the incoming data communication, what should I have to change there?

**Comment by tttapa** [comment]
Just comment out the entire function. Then in your main .ino sketch, add code for MIDI input using your MIDI library of choice.

**Comment by hachimbala** [comment]
So I uncomment the whole function and then for the MIDI input I use other MIDI library,  right?

**Comment by tttapa** [comment]
Yes.

**Comment by hachimbala** [comment]
Ok, it is working! Thank you so much!
