### ISSUE TITLE
Fluxamasynth V3.0 shield uses serial for device so not available for debug.

### ISSUE THREAD

**Issue by CoolGames** [tttapa/MIDI_controller#27]
Before opening a new issue, please read the [installation instructions](https://github.com/tttapa/MIDI_controller#installation) in the README. Also check if your question is answered in the [Wiki](https://github.com/tttapa/MIDI_controller/wiki) or in a [previous issue](https://github.com/tttapa/MIDI_controller/issues?q=is%3Aissue).   
If you do create a new issue, please follow the template below.  
--- (delete these first lines) ---

## Description of the problem or question
Serial Print not available for Fluxamasynth because the serial is output to pin 4
to the MIDI Shield at 31250 baud.

## Steps to reproduce the problem
Plug Fluxamasynth into Arduino UNO
## NOTE:
Modern Dreams has been selling this as SAM2195 since before 2015 until replacement SAM2695 in 2015.
The [Dream.fr MIDI chip](https://www.dream.fr/devices.html#S2) is difficult to obtain otherwise.
There are significant number of projects online with the earlier version of the shield.
It was never discovered to be documented for use as a MIDI Device.
Recently in 2016, the creator merged with AS220 to increase technical support.

### Hardware
Inland Arduino UNO r3 Breadboard Kit 341966
Fluxamasynth from Modern Devices containing Dream SAM2695 MIDI on a chip.

![fluxamasynthshieldr3sch](https://user-images.githubusercontent.com/149711/38149080-2818a1d8-3427-11e8-996c-3c1fc25ffed9.png)

**Arduino board**:  Inland Arduino UNO r3
**Schematic**: 

![arduino_uno_rev3-schematic](https://user-images.githubusercontent.com/149711/38149104-3a00fada-3427-11e8-8167-ebdb3a05ae1c.png)

### Software versions:

**MIDI Controller library**: 3.0.0
**Arduino IDE**: 1.8.5  
**Operating System**: Ubuntu Studio
**Operating System version**:  17.10

### Settings in the IDE
Add library for [Fluxamasynth from Github](https://github.com/moderndevice/Fluxamasynth-Shield)

### Full code 

```cpp
#include "Fluxamasynth.h"


Fluxamasynth synth;    // create a synth object


void setup() {
  // put your setup code here, to run once:
  Serial.begin(31250);    //  Set MIDI baud rate:

  synth.midiReset();            // Do a complete MIDI reset

}

void loop() {
  // put your main code here, to run repeatedly:


}
```

## Steps taken to try to diagnose or solve the problem
Can't begin due to design constraint

Unable to try the MIDI debug mode,
 Unable to initiate then use a MIDI monitor such as kmidimon

## The goal of your project and additional information

Goal is to create a USB MIDI Device that appears in Rosegarden and other MIDI applications
as a Roland MT-32 used to do with DIN5.
Now using new Roland Go Keys 61k over USB Device and Host for functional comparison.

**Comment by tttapa** [comment]
This library does not support relaying MIDI messages from the USB port to the synth chip, if that's what you want to do.

If you just want to send MIDI to the synth using the library, you can use a SoftwareSerial port on pin 4:
`SoftwarSerialMIDI_Interface(SoftwareSerial &serial, unsigned long baud)`.
