### ISSUE TITLE
Problem with DigitalCC

### ISSUE THREAD

**Issue by TheProgWalrus** [tttapa/MIDI_controller#30]
Hi, 
I cannot manage to install the DigitalCC class in order to use the switches as MIDI_CC controls. Is there a release of the MIDI_CONTROLLER library with this class already implemented? Or is there a tutorial that can explain me how to do this? Many thanks.

**Comment by tttapa** [comment]
Just create two new files (CTRL+SHIFT+N in the IDE): `DigitalCC.h` and DigitalCC.cpp`. Then just paste the code from the [wiki](https://github.com/tttapa/MIDI_controller/wiki/Custom-MIDI-controls) into the respective files.  
Finally, include the new file by using `#include "DigitalCC.h"` into your main sketch.  In this sketch, you can then instantiate DigitalCC objects.

**Comment by TheProgWalrus** [comment]
Mamy thanks. And is  the switch  with this instruction?

**Comment by TheProgWalrus** [comment]
*is the switch latched

**Comment by tttapa** [comment]
No, it's a normal momentary pushbutton.

**Comment by TheProgWalrus** [comment]
Thank you so much
