### ISSUE TITLE
Firmware link

### ISSUE THREAD

**Issue by elkavo** [tttapa/MIDI_controller#36]
Dear tttapa,

I'm very interrested in your project. 

It is to be used on a Arduino Mega. So I have to flash the firmware.

But the link to the Arduino firmware is not working. I can't find the Atmega16u2 firmware on the arduino github site either.

I'v found one on another site but I'm not sure if that is the correct firmware.

Would you know where I can download the software.

With regards

**Comment by DH1KLM** [comment]
i think this is the object of desire.
[https://github.com/arduino/ArduinoCore-avr/tree/master/firmwares/atmegaxxu2/arduino-usbserial](url)
There you can also find the .hex file

**Comment by elkavo** [comment]
Thank you!

**Comment by tttapa** [comment]
Seems like they moved all hardware-specific code into a separate repository. I'll have to update the links in the next revision.

**Comment by tttapa** [comment]
Fixed in 1ecbd2c86e2268b36391db0ae5a5390cdbe90b8a.
