### ISSUE TITLE
Encoder problem only CC or CCW

### ISSUE THREAD

**Issue by Mazzolo** [tttapa/MIDI_controller#37]
Hi, I'm new, I'm looking for build my dj controller. I have a problem. My encoder go only in one direction, or CC or CCW. I had try al settings in the example but nothing. Please help me.

**Comment by Mazzolo** [comment]
I try all settings and connection are good. The ground is on central pin of encoder. I try another sketch for  encoder, but not midi, and it works. So I think that hardware is good.

**Comment by tttapa** [comment]
What DJ/DAW software are you using?

**Comment by Mazzolo** [comment]
I'm  using traktor at the moment with hairless midi, and it gives always the same value in ccw and cw in debug. I buy on amazon arduino leonardo and I'm waiting to try with it

**Comment by Mazzolo** [comment]
I'm  using traktor at the moment with hairless midi, and it gives always the same value in ccw and cw in debug. I buy on amazon arduino leonardo and I'm waiting to try with it
