### ISSUE TITLE
Is it possible setup 2 encoder? I apologize for the previous post

### ISSUE THREAD

**Issue by Mazzolo** [tttapa/MIDI_controller#38]
I apologize to you. Your library works very well. I had to reinstall arduino IDE and clean register. Now it works good. Thank you, I'm very sorry but now I vahe another problem. It's possible use two encoder with this library?  I try to create  this two string:
RotaryEncoder enc1(0,1).....
Rotary Encoder enc2(2,3)......
but in this way it doesn't work. I will be very happy if you could help me. Thank you so much

**Comment by tttapa** [comment]
Yes, of course it's possible.

Please post your exact code and error messages.

**Comment by tttapa** [comment]
Glad to hear!
