### ISSUE TITLE
RAM problem

### ISSUE THREAD

**Issue by fredmorais** [tttapa/MIDI_controller#40]
Hello,

First of all thank you so much for your work, this is amazing!

I want to build a MIDI device with around 150 buttons, 17 faders and 5 encoders. You said in a previous issue that this consumes alot of RAM. Would an arduino mega be able to manage this? Or should I go for another board? If so, which one specifically?

Keep up the awesome work and thank you for bringing so much to the community!!

Yours faithfuly

**Comment by tttapa** [comment]
I don't know. I'd recommend a Teensy. A Mega might work, but I'm not sure.
