### ISSUE TITLE
Flashing back to serial - firmware not found

### ISSUE THREAD

**Issue by mungewell** [tttapa/MIDI_controller#52]
The script to flash Arduino back to serial F/W fails. Looks like the firmware image it is trying to download has moved

```
$ wget  "https://raw.githubusercontent.com/arduino/Arduino/master/hardware/arduino/avr/firmwares/atmegaxxu2/arduino-usbserial/Arduino-usbserial-atmega16u2-Uno-Rev3.hex"
--2018-06-28 19:19:15--  https://raw.githubusercontent.com/arduino/Arduino/master/hardware/arduino/avr/firmwares/atmegaxxu2/arduino-usbserial/Arduino-usbserial-atmega16u2-Uno-Rev3.hex
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.52.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.52.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-06-28 19:19:17 ERROR 404: Not Found.
```

Is it looking for this....?
https://raw.githubusercontent.com/arduino/ArduinoCore-avr/master/firmwares/atmegaxxu2/UNO-dfu_and_usbserial_combined.hex

**Comment by tttapa** [comment]
Yes it is, they split up the Arduino repository. I'll fix it in the next release. For now, you can just manually change the link.

**Comment by mungewell** [comment]
Ok, great.

You might want to fix the 'Y/n' question bit. If you just press enter it takes it as 'no' despite the 'Y' be a capital. ;-)

**Comment by tttapa** [comment]
You're right, added it to my TODO list :)
