### ISSUE TITLE
Difference between this lib and Arduino Midi Library

### ISSUE THREAD

**Issue by LouWii** [tttapa/MIDI_controller#64]
Hi,

This is not an issue, but more of a general question.

I'm just starting to learn Arduino dev, and I'm having a hard time to get my head around a thing.

Arduino has MIDI support through https://github.com/FortySevenEffects/arduino_midi_library

I understand that your library has a layer for handling controls (buttons etc...) but apart from that, is this the same as the midi library above? Is your lib using the other lib? Or are they completely different?

Thanks

**Comment by tttapa** [comment]
The MIDI Controller library has support for sending MIDI (either over a Serial interface, or over the USB interface), but other than that, it's different from the FortySevenEffects MIDI library.

Sending MIDI over Serial is handled by the MIDI Controller library itself, without external dependencies.  
For sending MIDI over USB, the MIDIUSB library is used.

The main goal of the FortySevenEffects MIDI library is to have complete and general purpose MIDI support on Arduino.  
The MIDI Controller library is more specific, it reads input devices and sends out MIDI as a MIDI controller. This means that you can use it to send normal MIDI messages as well, but it's not the main focus of the library.

**Comment by LouWii** [comment]
That makes sense. Thanks!
