### ISSUE TITLE
Daisy chained mux

### ISSUE THREAD

**Issue by jackojacek** [tttapa/MIDI_controller#67]
### Hardware

Arduino Micro

### Software versions:

**MIDI Controller library**: ? 3.0.0 ?  
**Arduino IDE**: ? 1.8.4 ?  
**Operating System**: OSX
**Operating System version**: ? 10, 16.04, ... ?  
(**Encoder library**): ? 1.4.1 ?  
(**MIDIUSB library**): ? 1.0.3 ? 

### Full code 

```cpp
// Your code here
```

**Comment by dds90** [comment]
Hi @jackojacek,
So, at the end, did you made the daisy chained the mux?
If yes, how did you do it?
