### ISSUE TITLE
a consistent increase in the value of the rotary encoder

### ISSUE THREAD

**Issue by santta** [tttapa/MIDI_controller#69]
## Description of the problem or question
Hello, I thank you for the wonderful library!!!
I want to use your library for Lightroom, too. 
Faced with the problem of using rotary encoder-only one value of the selected midi CC is sent when rotating to the right, also when rotating to the left, the same value is sent.
How can I adjust the sequential increase in the value of the desired midi CC, when turning the rotary encoder, like an analog potentiometer?

## Steps to reproduce the problem
when I turn the encoder that sends midi cc (date1) and (date2) . But the value (date2) does not increase with further rotation! lightroom doesn't see this action.

I have the exact same problem as MistrKernnunos. I need instructions on how to fix the problem

### Hardware

**Arduino board**:   Arduino Leonardo   

### Software versions:

**MIDI Controller library**:  3.1.0
**Arduino IDE**:  1.8.7
**Operating System**:  Windows10

![2018-11-27_00-04-03](https://user-images.githubusercontent.com/45362973/49042272-b2375200-f1d8-11e8-90d2-3fd0ab0d3e54.png)

**Comment by tttapa** [comment]
See #68.
