### ISSUE TITLE
digital button with Led while MIDI SEND

### ISSUE THREAD

**Issue by pandeagus** [tttapa/MIDI_controller#73]
hi tttapa.. 
can you teach me....

how i can use this code for turn on led with send note on
Digital button(2, C4, 1, velocity);

 I want that when the switch is pressed it can also turn on the led..

thanks...

**Comment by tttapa** [comment]
Hi, please see this [Wiki page](https://github.com/tttapa/MIDI_controller/wiki/Hardware#pushbuttons-and-switches).

**Comment by sincos5** [comment]
I know its a closed case, but.. What if you want to light the same LED with 2 diffrent buttons?
like, if you want to have an LED tomake shure that you pressed a button.
