### ISSUE TITLE
 Rotary encoder sends four signals instead of one.

### ISSUE THREAD

**Issue by santta** [tttapa/MIDI_controller#76]
## Description of the problem or question
Rotary encoder sends four signals instead of one. 
I tried to correct for different versions of the values ​​rotaryencoder.hpp (normal_encoder) and speedmultiplay (in the sketch). But the encoder still sends 4 signals at one turn. How can I fix this problem?

## Steps to reproduce the problem
RotaryEncoder.hpp

### Hardware
Mega2560

### Software versions:

MIDI Controller library: 3.1.0
Arduino IDE:  1.8.4
Windows10 
![screen](https://user-images.githubusercontent.com/45362973/52916117-c62cb480-32ec-11e9-8b4c-bc7f7ae4d366.jpg)

### Full code 

```cpp
#define USE_ROTARY_ENCODER
#include <MIDI_Controller.h>

const int speedMultiply = 1;     // No change in speed of the encoder (number of steps is multiplied by 1)

// Create a new instance of the class 'RotaryEncoder', called 'enc', on pin 2 and 3, controller number 0x14, on channel1,
// no change in speed (speed is multiplied by 1), it's used as a jog wheel, and the sign mode is set to two's complement.

//Энкодер
RotaryEncoder encoder(8, 9, 0x14, 9, speedMultiply, NORMAL_ENCODER, TWOS_COMPLEMENT);

//Кнопка
Digital button0(A1, 0x12, 3, 127);

//Кнопка энк
Digital button1(A15, 0x13, 2, 127);

//Мультики
AnalogMultiplex multiplexer1(A0, { 2, 3, 4, 5 } );

//Кнопки мультика 1
Digital button2[] = {
  {multiplexer1.pin(2), 0x19, 10},
  {multiplexer1.pin(1), 0x18, 8},
};

void setup() {}

void loop() {
  // Refresh the encoder (check whether the position has changed since last time, if so, send the difference over MIDI)
  MIDI_Controller.refresh();
}
```

## Steps taken to try to diagnose or solve the problem
? Tried the MIDI debug mode, used a MIDI monitor, ... ?

## The goal of your project and aditional information
![default](https://user-images.githubusercontent.com/45362973/52916213-9f22b280-32ed-11e9-9094-b4b26a16c0ce.jpg)

**Comment by tttapa** [comment]
Then you have a very strange encoder. Did you try using `NORMAL_ENCODER * 4`?

**Comment by santta** [comment]
Yes, I tried this value, but nothing has changed. There may be a problem in the encoder itself, I will try to connect another one.

**Comment by santta** [comment]
I installed another encoder (100% good) - four signals are sent again.

**Comment by tttapa** [comment]
I have no idea, to be honest.

Does changing the value to 1 result in 16 messages?

**Comment by santta** [comment]
I have now determined that the problem with the arduino IDE is on my PC. For some reason, the program does not work correctly.
