### ISSUE TITLE
Change device name

### ISSUE THREAD

**Issue by leo-combes** [tttapa/MIDI_controller#78]
Thanks for sharing this excellent work.
Is there any way to change how the MIDI device is identified when connected? For example in my case it is identified as "MIDI Arduino DUE" or something similar. Is it possible to change this?

Thank you.

**Comment by tttapa** [comment]
The name is not part of the MIDI Controller library, it is handled by the MIDIUSB library:
https://github.com/arduino-libraries/MIDIUSB/issues/37

**Comment by leo-combes** [comment]
Thanks!
